Compile on stable
google/rust_icu pull request #187
Opened 2020-11-08 16:44 UTC by Koxiaet

This PR allows `rust_icu` to compile using stable Rust by removing the unused `#![feature(try_trait)]` attributes in the `build.rs`s. I also fixed a couple Clippy warnings there and documented the dependency on Clang (I didn't have Clang installed and compilation failed as it couldn't find `stddef.h`.

2020-11-08 16:52 UTC, Koxiaet commented
@googlebot I signed it!

2020-11-08 19:56 UTC, Koxiaet commented
I reworked `ufmt` to be based on a tuple of types that implement the sealed `FormatArg` trait. This does mean it now only works with up to 26 arguments, but that can be increased if you want to - I only stopped at 26 because I ran out of letters. The advantage is we get to drop the `transmute` between `VaList` and `__va_list_tag`, and of course we don't have to use unstable features anymore. Additionally, since it's so easily possible now I supported not specifying the type at all - it will be guaranteed to implement the `FormatArg` trait, so it's safe.

I made not specifying any format arguments to the formatter a compile time instead of run time error using `compile_error!`, so we can drop that test.

I accidentally ran rustfmt on the crate root, so there are lots of random changes around the code base - sorry about that.

2020-11-08 22:02 UTC, filmil commented
Thank you for the pr. I’ll review this on Monday. As for the format run - I’ll run a format ahead of review so your diff will lose the formatting. I’ll let you know when ready. Thanks for your patience.

2020-11-09 17:27 UTC, filmil commented
Would you mind rebasing your change on top of the just-merged https://github.com/google/rust_icu/pull/188?

It should remove the formatting changes from this PR.

2020-11-09 17:50 UTC, filmil requested changes
Please rebase on top of current HEAD; I applied `cargo fmt` so the assorted formatting changes should disappear from your commits.

2020-11-09 17:50 UTC, filmil commented on rust_icu_udat/build.rs
> +                .with_context(|| "could not convert output to UTF8")?;
Thanks for cleaning this up, here and elsewhere!

2020-11-09 18:05 UTC, Koxiaet commented on rust_icu_umsg/src/lib.rs
> +        let result = message_format!(fmt, 43.43)?;
> This was specifically a test for the .clone() method, so I wouldn't remove it.

Thanks for noticing that, I added an `#[allow(clippy::redundant_clone)]` to make sure it doesn't happen again.

> at least the user has an opportunity to spell the type out explicitly.

I didn't remove the old method, it still works. But yeah I can see why you'd want to make users always write out the types explicitly.

2020-11-10 17:39 UTC, merged